package:
  name: python-mander
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  git_url: ../

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - mander
